### PR TITLE
add config for www. redirect

### PR DESCRIPTION
**Pull request by romainmenke**

### CODE REVIEW

**Comment by pieterbeulque** [comment]
LGTM. If you don't specify a `WWW-REDIRECT` env var, this doesn't touch anything, right?

**Comment by romainmenke** [comment]
@pieterbeulque 
that is correct. If `WWW-REDIRECT` is anything other than `WWW` or `NON-WWW` it will have zero impact.

**Comment by pieterbeulque** [comment]
Solved through FWD so maybe just leave this as-is?

**Comment by romainmenke** [comment]
Agree

**Pull request closed without merging**
